HGH for Sulfur (S) in PBE with NLCC
   16    6  050912 zatom, zion, date (ddmmyy)
   12 -101130 1 0 2002 0     pspcod, IXC, lmax, lloc, mmax, r2well
        0.33000000  2      1.49042820     -0.73313881 rloc nloc c1 c2
   2                                                       nsep
        0.37045712  2      6.18604810      0.00000000      s-projector
                                           2.57760787
        0.39772434  1      3.89113272      p-projector
                           0.00000000
        0.38621809         0.57499914      rcore, qcore (NLCC width and fraction)
