HGH for boron (B) in PBE with NLCC
    5    3  051812 zatom, zion, date (ddmmyy)
   12 -101130 0 0 2002 0     pspcod, IXC, lmax, lloc, mmax, r2well
        0.43249960  2     -4.26853158      0.59951279 rloc nloc c1 c2
   1                                       nsep
        0.37147150  1      6.30164101      s-projector
        0.33352310         0.43364348      rcore, qcore (NLCC width and fraction)
