Nonrelativistic HGH for magnesium (Mg) in PBE
   12  10  20130101                        zatom, zion, date (yymmdd)
   10   -101130 1 0 2002 0                 pspcod, IXC, lmax, lloc, mmax, r2well
        0.19275787  2      6.60406475     -1.60458432      rloc nloc c1 .. cnloc
   2                                                       nsep
        0.14834496  1     24.19311603      s-projector
        0.14470972  1     -9.56541706      p-projector
                           0.00000000


